# Form implementation generated from reading ui file 'dr_dlg_token.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgToken(object):
    def setupUi(self, dlgToken):
        dlgToken.setObjectName("dlgToken")
        dlgToken.resize(362, 158)
        dlgToken.setMinimumSize(QtCore.QSize(362, 158))
        dlgToken.setMaximumSize(QtCore.QSize(362, 158))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        dlgToken.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgToken.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(dlgToken)
        self.formLayout.setObjectName("formLayout")
        self.lblAuthToken = QtWidgets.QLabel(dlgToken)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lblAuthToken.setFont(font)
        self.lblAuthToken.setObjectName("lblAuthToken")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblAuthToken)
        self.txtAuthToken = QtWidgets.QLineEdit(dlgToken)
        self.txtAuthToken.setMaxLength(59)
        self.txtAuthToken.setObjectName("txtAuthToken")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtAuthToken)
        self.dlgTokenBtnBox = QtWidgets.QDialogButtonBox(dlgToken)
        self.dlgTokenBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgTokenBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgTokenBtnBox.setObjectName("dlgTokenBtnBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dlgTokenBtnBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem2)

        self.retranslateUi(dlgToken)
        self.dlgTokenBtnBox.accepted.connect(dlgToken.accept) # type: ignore
        self.dlgTokenBtnBox.rejected.connect(dlgToken.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgToken)

    def retranslateUi(self, dlgToken):
        _translate = QtCore.QCoreApplication.translate
        dlgToken.setWindowTitle(_translate("dlgToken", "Choose Auth Token"))
        self.lblAuthToken.setText(_translate("dlgToken", "Auth Token"))
