# Form implementation generated from reading ui file 'dr_dlg_payload.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgPayload(object):
    def setupUi(self, dlgPayload):
        dlgPayload.setObjectName("dlgPayload")
        dlgPayload.resize(362, 218)
        dlgPayload.setMinimumSize(QtCore.QSize(362, 218))
        dlgPayload.setMaximumSize(QtCore.QSize(397, 218))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        dlgPayload.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgPayload.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(dlgPayload)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem)
        self.lblWebhook = QtWidgets.QLabel(dlgPayload)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lblWebhook.setFont(font)
        self.lblWebhook.setObjectName("lblWebhook")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblWebhook)
        self.txtWebhook = QtWidgets.QLineEdit(dlgPayload)
        self.txtWebhook.setMaxLength(1000)
        self.txtWebhook.setObjectName("txtWebhook")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtWebhook)
        self.lblFolderName = QtWidgets.QLabel(dlgPayload)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblFolderName.setFont(font)
        self.lblFolderName.setObjectName("lblFolderName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFolderName)
        self.txtFolderName = QtWidgets.QLineEdit(dlgPayload)
        self.txtFolderName.setObjectName("txtFolderName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtFolderName)
        self.lblRPayloadName = QtWidgets.QLabel(dlgPayload)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblRPayloadName.setFont(font)
        self.lblRPayloadName.setObjectName("lblRPayloadName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblRPayloadName)
        self.txtRPayloadName = QtWidgets.QLineEdit(dlgPayload)
        self.txtRPayloadName.setObjectName("txtRPayloadName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtRPayloadName)
        self.lblHPayloadName = QtWidgets.QLabel(dlgPayload)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblHPayloadName.setFont(font)
        self.lblHPayloadName.setObjectName("lblHPayloadName")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblHPayloadName)
        self.txtHPayloadName = QtWidgets.QLineEdit(dlgPayload)
        self.txtHPayloadName.setObjectName("txtHPayloadName")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtHPayloadName)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem1)
        self.dlgPayloadBtnBox = QtWidgets.QDialogButtonBox(dlgPayload)
        self.dlgPayloadBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgPayloadBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgPayloadBtnBox.setObjectName("dlgPayloadBtnBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dlgPayloadBtnBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem2)
        self.chkAddToRegistry = QtWidgets.QCheckBox(dlgPayload)
        self.chkAddToRegistry.setObjectName("chkAddToRegistry")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.chkAddToRegistry)

        self.retranslateUi(dlgPayload)
        self.dlgPayloadBtnBox.accepted.connect(dlgPayload.accept) # type: ignore
        self.dlgPayloadBtnBox.rejected.connect(dlgPayload.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgPayload)

    def retranslateUi(self, dlgPayload):
        _translate = QtCore.QCoreApplication.translate
        dlgPayload.setWindowTitle(_translate("dlgPayload", "Payload Generator"))
        self.lblWebhook.setText(_translate("dlgPayload", "Webhook"))
        self.lblFolderName.setText(_translate("dlgPayload", "Folder Name"))
        self.lblRPayloadName.setText(_translate("dlgPayload", "Regular Payload Name"))
        self.lblHPayloadName.setText(_translate("dlgPayload", "Hidden Payload Name"))
        self.chkAddToRegistry.setText(_translate("dlgPayload", "Add to Windows Registry"))
