# Form implementation generated from reading ui file 'dr_dlg_server.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgServer(object):
    def setupUi(self, dlgServer):
        dlgServer.setObjectName("dlgServer")
        dlgServer.resize(362, 158)
        dlgServer.setMinimumSize(QtCore.QSize(362, 158))
        dlgServer.setMaximumSize(QtCore.QSize(362, 158))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        dlgServer.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgServer.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(dlgServer)
        self.formLayout.setObjectName("formLayout")
        self.lblGuildID = QtWidgets.QLabel(dlgServer)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lblGuildID.setFont(font)
        self.lblGuildID.setObjectName("lblGuildID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblGuildID)
        self.txtGuildID = QtWidgets.QLineEdit(dlgServer)
        self.txtGuildID.setMaxLength(18)
        self.txtGuildID.setObjectName("txtGuildID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtGuildID)
        self.dlgServerBtnBox = QtWidgets.QDialogButtonBox(dlgServer)
        self.dlgServerBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgServerBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgServerBtnBox.setObjectName("dlgServerBtnBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dlgServerBtnBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem2)

        self.retranslateUi(dlgServer)
        self.dlgServerBtnBox.accepted.connect(dlgServer.accept) # type: ignore
        self.dlgServerBtnBox.rejected.connect(dlgServer.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgServer)

    def retranslateUi(self, dlgServer):
        _translate = QtCore.QCoreApplication.translate
        dlgServer.setWindowTitle(_translate("dlgServer", "Choose Server"))
        self.lblGuildID.setText(_translate("dlgServer", "Server ID"))
