# Form implementation generated from reading ui file 'dr_dlg_task_still_running.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgTaskStillRunning(object):
    def setupUi(self, dlgTaskStillRunning):
        dlgTaskStillRunning.setObjectName("dlgTaskStillRunning")
        dlgTaskStillRunning.resize(362, 158)
        dlgTaskStillRunning.setMinimumSize(QtCore.QSize(362, 158))
        dlgTaskStillRunning.setMaximumSize(QtCore.QSize(362, 158))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        dlgTaskStillRunning.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgTaskStillRunning.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(dlgTaskStillRunning)
        self.formLayout.setObjectName("formLayout")
        self.lblTitle = QtWidgets.QLabel(dlgTaskStillRunning)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTitle)
        self.lblTaskDesc = QtWidgets.QLabel(dlgTaskStillRunning)
        self.lblTaskDesc.setObjectName("lblTaskDesc")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.lblTaskDesc)
        self.dlgTaskStillRunningBtnBox = QtWidgets.QDialogButtonBox(dlgTaskStillRunning)
        self.dlgTaskStillRunningBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgTaskStillRunningBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgTaskStillRunningBtnBox.setCenterButtons(True)
        self.dlgTaskStillRunningBtnBox.setObjectName("dlgTaskStillRunningBtnBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dlgTaskStillRunningBtnBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem2)

        self.retranslateUi(dlgTaskStillRunning)
        self.dlgTaskStillRunningBtnBox.accepted.connect(dlgTaskStillRunning.accept) # type: ignore
        self.dlgTaskStillRunningBtnBox.rejected.connect(dlgTaskStillRunning.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgTaskStillRunning)

    def retranslateUi(self, dlgTaskStillRunning):
        _translate = QtCore.QCoreApplication.translate
        dlgTaskStillRunning.setWindowTitle(_translate("dlgTaskStillRunning", "Task Still Running"))
        self.lblTitle.setText(_translate("dlgTaskStillRunning", "A task is still running!"))
        self.lblTaskDesc.setText(_translate("dlgTaskStillRunning", "Please stop all tasks before closing Discord Raidkit"))
