# Form implementation generated from reading ui file 'dr_dlg_improper_token.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgImproperToken(object):
    def setupUi(self, dlgImproperToken):
        dlgImproperToken.setObjectName("dlgImproperToken")
        dlgImproperToken.resize(362, 158)
        dlgImproperToken.setMinimumSize(QtCore.QSize(362, 158))
        dlgImproperToken.setMaximumSize(QtCore.QSize(362, 158))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        dlgImproperToken.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgImproperToken.setWindowIcon(icon)
        self.dlgImproperTokenBtnBox = QtWidgets.QDialogButtonBox(dlgImproperToken)
        self.dlgImproperTokenBtnBox.setGeometry(QtCore.QRect(248, 110, 100, 32))
        self.dlgImproperTokenBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgImproperTokenBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgImproperTokenBtnBox.setCenterButtons(True)
        self.dlgImproperTokenBtnBox.setObjectName("dlgImproperTokenBtnBox")
        self.lblTitle = QtWidgets.QLabel(dlgImproperToken)
        self.lblTitle.setGeometry(QtCore.QRect(20, 20, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.lblImproperTokenDesc1 = QtWidgets.QLabel(dlgImproperToken)
        self.lblImproperTokenDesc1.setGeometry(QtCore.QRect(20, 60, 321, 16))
        self.lblImproperTokenDesc1.setObjectName("lblImproperTokenDesc1")
        self.lblImproperTokenDesc2 = QtWidgets.QLabel(dlgImproperToken)
        self.lblImproperTokenDesc2.setGeometry(QtCore.QRect(20, 80, 331, 16))
        self.lblImproperTokenDesc2.setObjectName("lblImproperTokenDesc2")
        self.lblImpropertokenDesc3 = QtWidgets.QLabel(dlgImproperToken)
        self.lblImpropertokenDesc3.setGeometry(QtCore.QRect(20, 100, 161, 16))
        self.lblImpropertokenDesc3.setObjectName("lblImpropertokenDesc3")

        self.retranslateUi(dlgImproperToken)
        self.dlgImproperTokenBtnBox.accepted.connect(dlgImproperToken.accept) # type: ignore
        self.dlgImproperTokenBtnBox.rejected.connect(dlgImproperToken.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgImproperToken)

    def retranslateUi(self, dlgImproperToken):
        _translate = QtCore.QCoreApplication.translate
        dlgImproperToken.setWindowTitle(_translate("dlgImproperToken", "Improper Token"))
        self.lblTitle.setText(_translate("dlgImproperToken", "Improper Token Passed"))
        self.lblImproperTokenDesc1.setText(_translate("dlgImproperToken", "Please double check the bot configuration."))
        self.lblImproperTokenDesc2.setText(_translate("dlgImproperToken", "If you\'re certain the token is correct,"))
        self.lblImpropertokenDesc3.setText(_translate("dlgImproperToken", "submit an issue on GitHub!"))
