# Form implementation generated from reading ui file 'dr_dlg_nuke.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgNuke(object):
    def setupUi(self, dlgNuke):
        dlgNuke.setObjectName("dlgNuke")
        dlgNuke.resize(362, 178)
        dlgNuke.setMinimumSize(QtCore.QSize(362, 178))
        dlgNuke.setMaximumSize(QtCore.QSize(362, 178))
        font = QtGui.QFont()
        font.setFamily("Arial")
        dlgNuke.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgNuke.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(dlgNuke)
        self.formLayout.setObjectName("formLayout")
        self.lblGuildID = QtWidgets.QLabel(dlgNuke)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGuildID.setFont(font)
        self.lblGuildID.setObjectName("lblGuildID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblGuildID)
        self.txtGuildID = QtWidgets.QLineEdit(dlgNuke)
        self.txtGuildID.setMaxLength(18)
        self.txtGuildID.setObjectName("txtGuildID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtGuildID)
        self.lblExclusions = QtWidgets.QLabel(dlgNuke)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblExclusions.setFont(font)
        self.lblExclusions.setObjectName("lblExclusions")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblExclusions)
        self.txtExclusions = QtWidgets.QLineEdit(dlgNuke)
        self.txtExclusions.setMaxLength(18)
        self.txtExclusions.setObjectName("txtExclusions")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtExclusions)
        self.lblNukeExclusionsDesc1 = QtWidgets.QLabel(dlgNuke)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lblNukeExclusionsDesc1.setFont(font)
        self.lblNukeExclusionsDesc1.setObjectName("lblNukeExclusionsDesc1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.lblNukeExclusionsDesc1)
        self.lblNukeExclusionsDesc2 = QtWidgets.QLabel(dlgNuke)
        self.lblNukeExclusionsDesc2.setObjectName("lblNukeExclusionsDesc2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.lblNukeExclusionsDesc2)
        self.dlgNukeBtnBox = QtWidgets.QDialogButtonBox(dlgNuke)
        self.dlgNukeBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgNukeBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgNukeBtnBox.setObjectName("dlgNukeBtnBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dlgNukeBtnBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem)

        self.retranslateUi(dlgNuke)
        self.dlgNukeBtnBox.accepted.connect(dlgNuke.accept) # type: ignore
        self.dlgNukeBtnBox.rejected.connect(dlgNuke.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgNuke)

    def retranslateUi(self, dlgNuke):
        _translate = QtCore.QCoreApplication.translate
        dlgNuke.setWindowTitle(_translate("dlgNuke", "Nuke Server"))
        self.lblGuildID.setText(_translate("dlgNuke", "Server ID:"))
        self.lblExclusions.setText(_translate("dlgNuke", "Exclude IDs:"))
        self.lblNukeExclusionsDesc1.setText(_translate("dlgNuke", "Excludes members from nukes; use member IDs"))
        self.lblNukeExclusionsDesc2.setText(_translate("dlgNuke", "You can set multiple exclusions; seperate by \\,"))
