# Form implementation generated from reading ui file 'dr_dlg_confirmation.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgConfirmation(object):
    def setupUi(self, dlgConfirmation):
        dlgConfirmation.setObjectName("dlgConfirmation")
        dlgConfirmation.resize(362, 158)
        dlgConfirmation.setMinimumSize(QtCore.QSize(362, 158))
        dlgConfirmation.setMaximumSize(QtCore.QSize(362, 158))
        font = QtGui.QFont()
        font.setFamily("Arial")
        dlgConfirmation.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgConfirmation.setWindowIcon(icon)
        self.dlgConfirmationBtnBox = QtWidgets.QDialogButtonBox(dlgConfirmation)
        self.dlgConfirmationBtnBox.setGeometry(QtCore.QRect(150, 110, 198, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.dlgConfirmationBtnBox.setFont(font)
        self.dlgConfirmationBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgConfirmationBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgConfirmationBtnBox.setObjectName("dlgConfirmationBtnBox")
        self.lblConfirmation1 = QtWidgets.QLabel(dlgConfirmation)
        self.lblConfirmation1.setGeometry(QtCore.QRect(20, 20, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lblConfirmation1.setFont(font)
        self.lblConfirmation1.setObjectName("lblConfirmation1")
        self.lblConfirmation2 = QtWidgets.QLabel(dlgConfirmation)
        self.lblConfirmation2.setGeometry(QtCore.QRect(20, 40, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lblConfirmation2.setFont(font)
        self.lblConfirmation2.setObjectName("lblConfirmation2")

        self.retranslateUi(dlgConfirmation)
        self.dlgConfirmationBtnBox.accepted.connect(dlgConfirmation.accept) # type: ignore
        self.dlgConfirmationBtnBox.rejected.connect(dlgConfirmation.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgConfirmation)

    def retranslateUi(self, dlgConfirmation):
        _translate = QtCore.QCoreApplication.translate
        dlgConfirmation.setWindowTitle(_translate("dlgConfirmation", "Confirmation"))
        self.lblConfirmation1.setText(_translate("dlgConfirmation", "Are you sure you want to leave every server?"))
        self.lblConfirmation2.setText(_translate("dlgConfirmation", "Press OK to confirm"))
