# Form implementation generated from reading ui file 'dr_dlg_admin.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAdmin(object):
    def setupUi(self, dlgAdmin):
        dlgAdmin.setObjectName("dlgAdmin")
        dlgAdmin.resize(362, 158)
        dlgAdmin.setMinimumSize(QtCore.QSize(362, 158))
        dlgAdmin.setMaximumSize(QtCore.QSize(362, 158))
        font = QtGui.QFont()
        font.setFamily("Arial")
        dlgAdmin.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgAdmin.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(dlgAdmin)
        self.formLayout.setObjectName("formLayout")
        self.lblGuildID = QtWidgets.QLabel(dlgAdmin)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGuildID.setFont(font)
        self.lblGuildID.setObjectName("lblGuildID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblGuildID)
        self.txtGuildID = QtWidgets.QLineEdit(dlgAdmin)
        self.txtGuildID.setMaxLength(18)
        self.txtGuildID.setObjectName("txtGuildID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtGuildID)
        self.lblUserID = QtWidgets.QLabel(dlgAdmin)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblUserID.setFont(font)
        self.lblUserID.setObjectName("lblUserID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblUserID)
        self.txtUserID = QtWidgets.QLineEdit(dlgAdmin)
        self.txtUserID.setMaxLength(18)
        self.txtUserID.setObjectName("txtUserID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtUserID)
        self.lblRolename = QtWidgets.QLabel(dlgAdmin)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblRolename.setFont(font)
        self.lblRolename.setObjectName("lblRolename")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblRolename)
        self.txtRolename = QtWidgets.QLineEdit(dlgAdmin)
        self.txtRolename.setMaxLength(100)
        self.txtRolename.setObjectName("txtRolename")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtRolename)
        self.dlgAdminBtnBox = QtWidgets.QDialogButtonBox(dlgAdmin)
        self.dlgAdminBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgAdminBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgAdminBtnBox.setObjectName("dlgAdminBtnBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dlgAdminBtnBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem)

        self.retranslateUi(dlgAdmin)
        self.dlgAdminBtnBox.accepted.connect(dlgAdmin.accept) # type: ignore
        self.dlgAdminBtnBox.rejected.connect(dlgAdmin.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgAdmin)
        dlgAdmin.setTabOrder(self.txtGuildID, self.txtUserID)
        dlgAdmin.setTabOrder(self.txtUserID, self.txtRolename)

    def retranslateUi(self, dlgAdmin):
        _translate = QtCore.QCoreApplication.translate
        dlgAdmin.setWindowTitle(_translate("dlgAdmin", "Grant Admin"))
        self.lblGuildID.setText(_translate("dlgAdmin", "Server ID:"))
        self.lblUserID.setText(_translate("dlgAdmin", "User ID:"))
        self.lblRolename.setText(_translate("dlgAdmin", "Role Name:"))
