# Form implementation generated from reading ui file 'dr_dlg_mass_nuke.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgMassNuke(object):
    def setupUi(self, dlgMassNuke):
        dlgMassNuke.setObjectName("dlgMassNuke")
        dlgMassNuke.resize(362, 178)
        dlgMassNuke.setMinimumSize(QtCore.QSize(362, 178))
        dlgMassNuke.setMaximumSize(QtCore.QSize(362, 178))
        font = QtGui.QFont()
        font.setFamily("Arial")
        dlgMassNuke.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgMassNuke.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(dlgMassNuke)
        self.formLayout.setObjectName("formLayout")
        self.lblExclusions = QtWidgets.QLabel(dlgMassNuke)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblExclusions.setFont(font)
        self.lblExclusions.setObjectName("lblExclusions")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblExclusions)
        self.txtExclusions = QtWidgets.QLineEdit(dlgMassNuke)
        self.txtExclusions.setMaxLength(18)
        self.txtExclusions.setObjectName("txtExclusions")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtExclusions)
        self.lblMassNukeExclusionsDesc1 = QtWidgets.QLabel(dlgMassNuke)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lblMassNukeExclusionsDesc1.setFont(font)
        self.lblMassNukeExclusionsDesc1.setObjectName("lblMassNukeExclusionsDesc1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.lblMassNukeExclusionsDesc1)
        self.lblMassNukeExclusionsDesc2 = QtWidgets.QLabel(dlgMassNuke)
        self.lblMassNukeExclusionsDesc2.setObjectName("lblMassNukeExclusionsDesc2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.lblMassNukeExclusionsDesc2)
        self.dlgMassNukeBtnBox = QtWidgets.QDialogButtonBox(dlgMassNuke)
        self.dlgMassNukeBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgMassNukeBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgMassNukeBtnBox.setObjectName("dlgMassNukeBtnBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dlgMassNukeBtnBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem)

        self.retranslateUi(dlgMassNuke)
        self.dlgMassNukeBtnBox.accepted.connect(dlgMassNuke.accept) # type: ignore
        self.dlgMassNukeBtnBox.rejected.connect(dlgMassNuke.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgMassNuke)

    def retranslateUi(self, dlgMassNuke):
        _translate = QtCore.QCoreApplication.translate
        dlgMassNuke.setWindowTitle(_translate("dlgMassNuke", "Mass Nuke"))
        self.lblExclusions.setText(_translate("dlgMassNuke", "Exclude IDs:"))
        self.lblMassNukeExclusionsDesc1.setText(_translate("dlgMassNuke", "Excludes members from nukes; use member IDs"))
        self.lblMassNukeExclusionsDesc2.setText(_translate("dlgMassNuke", "You can set multiple exclusions; seperate by \\,"))
