# Form implementation generated from reading ui file 'dr_dlg_nicknames.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgNicknames(object):
    def setupUi(self, dlgNicknames):
        dlgNicknames.setObjectName("dlgNicknames")
        dlgNicknames.resize(362, 158)
        dlgNicknames.setMinimumSize(QtCore.QSize(362, 158))
        dlgNicknames.setMaximumSize(QtCore.QSize(362, 158))
        font = QtGui.QFont()
        font.setFamily("Arial")
        dlgNicknames.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgNicknames.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(dlgNicknames)
        self.formLayout.setObjectName("formLayout")
        self.lblGuildID = QtWidgets.QLabel(dlgNicknames)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGuildID.setFont(font)
        self.lblGuildID.setObjectName("lblGuildID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblGuildID)
        self.txtGuildID = QtWidgets.QLineEdit(dlgNicknames)
        self.txtGuildID.setMaxLength(18)
        self.txtGuildID.setObjectName("txtGuildID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtGuildID)
        self.lblNicknames = QtWidgets.QLabel(dlgNicknames)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblNicknames.setFont(font)
        self.lblNicknames.setObjectName("lblNicknames")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblNicknames)
        self.txtNicknames = QtWidgets.QLineEdit(dlgNicknames)
        self.txtNicknames.setMaxLength(32)
        self.txtNicknames.setObjectName("txtNicknames")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtNicknames)
        self.lblNicknamesDesc = QtWidgets.QLabel(dlgNicknames)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lblNicknamesDesc.setFont(font)
        self.lblNicknamesDesc.setObjectName("lblNicknamesDesc")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.lblNicknamesDesc)
        self.dlgNicknamesBtnBox = QtWidgets.QDialogButtonBox(dlgNicknames)
        self.dlgNicknamesBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgNicknamesBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgNicknamesBtnBox.setObjectName("dlgNicknamesBtnBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dlgNicknamesBtnBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem)

        self.retranslateUi(dlgNicknames)
        self.dlgNicknamesBtnBox.accepted.connect(dlgNicknames.accept) # type: ignore
        self.dlgNicknamesBtnBox.rejected.connect(dlgNicknames.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgNicknames)
        dlgNicknames.setTabOrder(self.txtGuildID, self.txtNicknames)

    def retranslateUi(self, dlgNicknames):
        _translate = QtCore.QCoreApplication.translate
        dlgNicknames.setWindowTitle(_translate("dlgNicknames", "Choose Nicknames"))
        self.lblGuildID.setText(_translate("dlgNicknames", "Server ID:"))
        self.lblNicknames.setText(_translate("dlgNicknames", "Nicknames:"))
        self.lblNicknamesDesc.setText(_translate("dlgNicknames", "You can set multiple nicknames; seperate by \\,"))
