# Form implementation generated from reading ui file 'dr_dlg_mass_nuke.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgMassNuke(object):
    def setupUi(self, dlgMassNuke):
        dlgMassNuke.setObjectName("dlgMassNuke")
        dlgMassNuke.resize(362, 178)
        dlgMassNuke.setMinimumSize(QtCore.QSize(362, 178))
        dlgMassNuke.setMaximumSize(QtCore.QSize(362, 178))
        font = QtGui.QFont()
        font.setFamily("Arial")
        dlgMassNuke.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.PNG"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgMassNuke.setWindowIcon(icon)
        self.dlgMassNukeBtnBox = QtWidgets.QDialogButtonBox(dlgMassNuke)
        self.dlgMassNukeBtnBox.setGeometry(QtCore.QRect(150, 130, 193, 28))
        self.dlgMassNukeBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgMassNukeBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgMassNukeBtnBox.setObjectName("dlgMassNukeBtnBox")
        self.lblExclusions = QtWidgets.QLabel(dlgMassNuke)
        self.lblExclusions.setGeometry(QtCore.QRect(20, 40, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblExclusions.setFont(font)
        self.lblExclusions.setObjectName("lblExclusions")
        self.txtExclusions = QtWidgets.QLineEdit(dlgMassNuke)
        self.txtExclusions.setGeometry(QtCore.QRect(130, 40, 212, 22))
        self.txtExclusions.setMaxLength(18)
        self.txtExclusions.setObjectName("txtExclusions")
        self.lblMassNukeExclusionsDesc1 = QtWidgets.QLabel(dlgMassNuke)
        self.lblMassNukeExclusionsDesc1.setGeometry(QtCore.QRect(20, 70, 321, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lblMassNukeExclusionsDesc1.setFont(font)
        self.lblMassNukeExclusionsDesc1.setObjectName("lblMassNukeExclusionsDesc1")
        self.lblMassNukeExclusionsDesc2 = QtWidgets.QLabel(dlgMassNuke)
        self.lblMassNukeExclusionsDesc2.setGeometry(QtCore.QRect(20, 90, 281, 16))
        self.lblMassNukeExclusionsDesc2.setObjectName("lblMassNukeExclusionsDesc2")

        self.retranslateUi(dlgMassNuke)
        self.dlgMassNukeBtnBox.accepted.connect(dlgMassNuke.accept) # type: ignore
        self.dlgMassNukeBtnBox.rejected.connect(dlgMassNuke.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgMassNuke)

    def retranslateUi(self, dlgMassNuke):
        _translate = QtCore.QCoreApplication.translate
        dlgMassNuke.setWindowTitle(_translate("dlgMassNuke", "Mass Nuke"))
        self.lblExclusions.setText(_translate("dlgMassNuke", "Exclude IDs:"))
        self.lblMassNukeExclusionsDesc1.setText(_translate("dlgMassNuke", "Excludes members from nukes; use member IDs"))
        self.lblMassNukeExclusionsDesc2.setText(_translate("dlgMassNuke", "You can set multiple exclusions; seperate by \\,"))
