# Form implementation generated from reading ui file 'dr_dlg_admin.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAdmin(object):
    def setupUi(self, dlgAdmin):
        dlgAdmin.setObjectName("dlgAdmin")
        dlgAdmin.resize(362, 158)
        dlgAdmin.setMinimumSize(QtCore.QSize(362, 158))
        dlgAdmin.setMaximumSize(QtCore.QSize(362, 158))
        font = QtGui.QFont()
        font.setFamily("Arial")
        dlgAdmin.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.PNG"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgAdmin.setWindowIcon(icon)
        self.dlgAdminBtnBox = QtWidgets.QDialogButtonBox(dlgAdmin)
        self.dlgAdminBtnBox.setGeometry(QtCore.QRect(150, 120, 193, 28))
        self.dlgAdminBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgAdminBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgAdminBtnBox.setObjectName("dlgAdminBtnBox")
        self.lblGuildID = QtWidgets.QLabel(dlgAdmin)
        self.lblGuildID.setGeometry(QtCore.QRect(20, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGuildID.setFont(font)
        self.lblGuildID.setObjectName("lblGuildID")
        self.txtGuildID = QtWidgets.QLineEdit(dlgAdmin)
        self.txtGuildID.setGeometry(QtCore.QRect(120, 20, 222, 22))
        self.txtGuildID.setMaxLength(18)
        self.txtGuildID.setObjectName("txtGuildID")
        self.lblUserID = QtWidgets.QLabel(dlgAdmin)
        self.lblUserID.setGeometry(QtCore.QRect(20, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblUserID.setFont(font)
        self.lblUserID.setObjectName("lblUserID")
        self.txtUserID = QtWidgets.QLineEdit(dlgAdmin)
        self.txtUserID.setGeometry(QtCore.QRect(120, 50, 222, 22))
        self.txtUserID.setMaxLength(18)
        self.txtUserID.setObjectName("txtUserID")
        self.lblRolename = QtWidgets.QLabel(dlgAdmin)
        self.lblRolename.setGeometry(QtCore.QRect(20, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblRolename.setFont(font)
        self.lblRolename.setObjectName("lblRolename")
        self.txtRolename = QtWidgets.QLineEdit(dlgAdmin)
        self.txtRolename.setGeometry(QtCore.QRect(120, 80, 222, 22))
        self.txtRolename.setMaxLength(100)
        self.txtRolename.setObjectName("txtRolename")

        self.retranslateUi(dlgAdmin)
        self.dlgAdminBtnBox.accepted.connect(dlgAdmin.accept) # type: ignore
        self.dlgAdminBtnBox.rejected.connect(dlgAdmin.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgAdmin)
        dlgAdmin.setTabOrder(self.txtGuildID, self.txtUserID)
        dlgAdmin.setTabOrder(self.txtUserID, self.txtRolename)

    def retranslateUi(self, dlgAdmin):
        _translate = QtCore.QCoreApplication.translate
        dlgAdmin.setWindowTitle(_translate("dlgAdmin", "Grant Admin"))
        self.lblGuildID.setText(_translate("dlgAdmin", "Server ID:"))
        self.lblUserID.setText(_translate("dlgAdmin", "User ID:"))
        self.lblRolename.setText(_translate("dlgAdmin", "Role Name:"))
