# Form implementation generated from reading ui file 'dr_dlg_nuke.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgNuke(object):
    def setupUi(self, dlgNuke):
        dlgNuke.setObjectName("dlgNuke")
        dlgNuke.resize(362, 178)
        dlgNuke.setMinimumSize(QtCore.QSize(362, 178))
        dlgNuke.setMaximumSize(QtCore.QSize(362, 178))
        font = QtGui.QFont()
        font.setFamily("Arial")
        dlgNuke.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.PNG"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgNuke.setWindowIcon(icon)
        self.dlgNukeBtnBox = QtWidgets.QDialogButtonBox(dlgNuke)
        self.dlgNukeBtnBox.setGeometry(QtCore.QRect(150, 130, 193, 28))
        self.dlgNukeBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgNukeBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgNukeBtnBox.setObjectName("dlgNukeBtnBox")
        self.lblGuildID = QtWidgets.QLabel(dlgNuke)
        self.lblGuildID.setGeometry(QtCore.QRect(20, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGuildID.setFont(font)
        self.lblGuildID.setObjectName("lblGuildID")
        self.txtGuildID = QtWidgets.QLineEdit(dlgNuke)
        self.txtGuildID.setGeometry(QtCore.QRect(130, 20, 212, 22))
        self.txtGuildID.setMaxLength(18)
        self.txtGuildID.setObjectName("txtGuildID")
        self.lblExclusions = QtWidgets.QLabel(dlgNuke)
        self.lblExclusions.setGeometry(QtCore.QRect(20, 50, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblExclusions.setFont(font)
        self.lblExclusions.setObjectName("lblExclusions")
        self.txtExclusions = QtWidgets.QLineEdit(dlgNuke)
        self.txtExclusions.setGeometry(QtCore.QRect(130, 50, 212, 22))
        self.txtExclusions.setMaxLength(18)
        self.txtExclusions.setObjectName("txtExclusions")
        self.lblNukeExclusionsDesc1 = QtWidgets.QLabel(dlgNuke)
        self.lblNukeExclusionsDesc1.setGeometry(QtCore.QRect(20, 80, 321, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lblNukeExclusionsDesc1.setFont(font)
        self.lblNukeExclusionsDesc1.setObjectName("lblNukeExclusionsDesc1")
        self.lblNukeExclusionsDesc2 = QtWidgets.QLabel(dlgNuke)
        self.lblNukeExclusionsDesc2.setGeometry(QtCore.QRect(20, 100, 281, 16))
        self.lblNukeExclusionsDesc2.setObjectName("lblNukeExclusionsDesc2")

        self.retranslateUi(dlgNuke)
        self.dlgNukeBtnBox.accepted.connect(dlgNuke.accept) # type: ignore
        self.dlgNukeBtnBox.rejected.connect(dlgNuke.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgNuke)

    def retranslateUi(self, dlgNuke):
        _translate = QtCore.QCoreApplication.translate
        dlgNuke.setWindowTitle(_translate("dlgNuke", "Nuke Server"))
        self.lblGuildID.setText(_translate("dlgNuke", "Server ID:"))
        self.lblExclusions.setText(_translate("dlgNuke", "Exclude IDs:"))
        self.lblNukeExclusionsDesc1.setText(_translate("dlgNuke", "Excludes members from nukes; use member IDs"))
        self.lblNukeExclusionsDesc2.setText(_translate("dlgNuke", "You can set multiple exclusions; seperate by \\,"))
