# Form implementation generated from reading ui file 'dr_dlg_messages.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgMessages(object):
    def setupUi(self, dlgMessages):
        dlgMessages.setObjectName("dlgMessages")
        dlgMessages.resize(362, 158)
        dlgMessages.setMinimumSize(QtCore.QSize(362, 158))
        dlgMessages.setMaximumSize(QtCore.QSize(362, 158))
        font = QtGui.QFont()
        font.setFamily("Arial")
        dlgMessages.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.PNG"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgMessages.setWindowIcon(icon)
        self.dlgMessagesBtnBox = QtWidgets.QDialogButtonBox(dlgMessages)
        self.dlgMessagesBtnBox.setGeometry(QtCore.QRect(150, 110, 193, 28))
        self.dlgMessagesBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgMessagesBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgMessagesBtnBox.setObjectName("dlgMessagesBtnBox")
        self.lblGuildID = QtWidgets.QLabel(dlgMessages)
        self.lblGuildID.setGeometry(QtCore.QRect(20, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGuildID.setFont(font)
        self.lblGuildID.setObjectName("lblGuildID")
        self.txtGuildID = QtWidgets.QLineEdit(dlgMessages)
        self.txtGuildID.setGeometry(QtCore.QRect(120, 20, 222, 22))
        self.txtGuildID.setMaxLength(18)
        self.txtGuildID.setObjectName("txtGuildID")
        self.lblMessages = QtWidgets.QLabel(dlgMessages)
        self.lblMessages.setGeometry(QtCore.QRect(20, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblMessages.setFont(font)
        self.lblMessages.setObjectName("lblMessages")
        self.txtMessages = QtWidgets.QLineEdit(dlgMessages)
        self.txtMessages.setGeometry(QtCore.QRect(120, 50, 222, 22))
        self.txtMessages.setMaxLength(2000)
        self.txtMessages.setObjectName("txtMessages")
        self.lblMessagesDesc = QtWidgets.QLabel(dlgMessages)
        self.lblMessagesDesc.setGeometry(QtCore.QRect(20, 80, 321, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lblMessagesDesc.setFont(font)
        self.lblMessagesDesc.setObjectName("lblMessagesDesc")

        self.retranslateUi(dlgMessages)
        self.dlgMessagesBtnBox.accepted.connect(dlgMessages.accept) # type: ignore
        self.dlgMessagesBtnBox.rejected.connect(dlgMessages.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgMessages)
        dlgMessages.setTabOrder(self.txtGuildID, self.txtMessages)

    def retranslateUi(self, dlgMessages):
        _translate = QtCore.QCoreApplication.translate
        dlgMessages.setWindowTitle(_translate("dlgMessages", "Choose Messages"))
        self.lblGuildID.setText(_translate("dlgMessages", "Server ID:"))
        self.lblMessages.setText(_translate("dlgMessages", "Messages:"))
        self.lblMessagesDesc.setText(_translate("dlgMessages", "You can set multiple messages; seperate by \\,"))
