# Form implementation generated from reading ui file 'dr_dlg_nicknames.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgNicknames(object):
    def setupUi(self, dlgNicknames):
        dlgNicknames.setObjectName("dlgNicknames")
        dlgNicknames.resize(362, 158)
        dlgNicknames.setMinimumSize(QtCore.QSize(362, 158))
        dlgNicknames.setMaximumSize(QtCore.QSize(362, 158))
        font = QtGui.QFont()
        font.setFamily("Arial")
        dlgNicknames.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.PNG"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgNicknames.setWindowIcon(icon)
        self.dlgNicknamesBtnBox = QtWidgets.QDialogButtonBox(dlgNicknames)
        self.dlgNicknamesBtnBox.setGeometry(QtCore.QRect(150, 110, 193, 28))
        self.dlgNicknamesBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgNicknamesBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dlgNicknamesBtnBox.setObjectName("dlgNicknamesBtnBox")
        self.lblNicknames = QtWidgets.QLabel(dlgNicknames)
        self.lblNicknames.setGeometry(QtCore.QRect(20, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblNicknames.setFont(font)
        self.lblNicknames.setObjectName("lblNicknames")
        self.txtNicknames = QtWidgets.QLineEdit(dlgNicknames)
        self.txtNicknames.setGeometry(QtCore.QRect(120, 50, 222, 22))
        self.txtNicknames.setMaxLength(32)
        self.txtNicknames.setObjectName("txtNicknames")
        self.lblNicknamesDesc = QtWidgets.QLabel(dlgNicknames)
        self.lblNicknamesDesc.setGeometry(QtCore.QRect(20, 80, 321, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lblNicknamesDesc.setFont(font)
        self.lblNicknamesDesc.setObjectName("lblNicknamesDesc")
        self.lblGuildID = QtWidgets.QLabel(dlgNicknames)
        self.lblGuildID.setGeometry(QtCore.QRect(20, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGuildID.setFont(font)
        self.lblGuildID.setObjectName("lblGuildID")
        self.txtGuildID = QtWidgets.QLineEdit(dlgNicknames)
        self.txtGuildID.setGeometry(QtCore.QRect(120, 20, 222, 22))
        self.txtGuildID.setMaxLength(18)
        self.txtGuildID.setObjectName("txtGuildID")

        self.retranslateUi(dlgNicknames)
        self.dlgNicknamesBtnBox.accepted.connect(dlgNicknames.accept) # type: ignore
        self.dlgNicknamesBtnBox.rejected.connect(dlgNicknames.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgNicknames)
        dlgNicknames.setTabOrder(self.txtGuildID, self.txtNicknames)

    def retranslateUi(self, dlgNicknames):
        _translate = QtCore.QCoreApplication.translate
        dlgNicknames.setWindowTitle(_translate("dlgNicknames", "Choose Nicknames"))
        self.lblNicknames.setText(_translate("dlgNicknames", "Nicknames:"))
        self.lblNicknamesDesc.setText(_translate("dlgNicknames", "You can set multiple nicknames; seperate by \\,"))
        self.lblGuildID.setText(_translate("dlgNicknames", "Server ID:"))
