# Form implementation generated from reading ui file 'dr_dlg_new_update.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgNewUpdate(object):
    def setupUi(self, dlgNewUpdate):
        dlgNewUpdate.setObjectName("dlgNewUpdate")
        dlgNewUpdate.resize(362, 188)
        dlgNewUpdate.setMinimumSize(QtCore.QSize(362, 188))
        dlgNewUpdate.setMaximumSize(QtCore.QSize(362, 188))
        font = QtGui.QFont()
        font.setFamily("Arial")
        dlgNewUpdate.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.PNG"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgNewUpdate.setWindowIcon(icon)
        self.dlgNewUpdateBtnBox = QtWidgets.QDialogButtonBox(dlgNewUpdate)
        self.dlgNewUpdateBtnBox.setGeometry(QtCore.QRect(160, 140, 193, 28))
        self.dlgNewUpdateBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dlgNewUpdateBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.No|QtWidgets.QDialogButtonBox.StandardButton.Yes)
        self.dlgNewUpdateBtnBox.setObjectName("dlgNewUpdateBtnBox")
        self.lblNewUpdateTitle = QtWidgets.QLabel(dlgNewUpdate)
        self.lblNewUpdateTitle.setGeometry(QtCore.QRect(20, 20, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblNewUpdateTitle.setFont(font)
        self.lblNewUpdateTitle.setObjectName("lblNewUpdateTitle")
        self.lblNewUpdateDesc1 = QtWidgets.QLabel(dlgNewUpdate)
        self.lblNewUpdateDesc1.setGeometry(QtCore.QRect(20, 60, 291, 16))
        self.lblNewUpdateDesc1.setObjectName("lblNewUpdateDesc1")
        self.lblNewUpdateDesc2 = QtWidgets.QLabel(dlgNewUpdate)
        self.lblNewUpdateDesc2.setGeometry(QtCore.QRect(20, 80, 321, 16))
        self.lblNewUpdateDesc2.setObjectName("lblNewUpdateDesc2")
        self.cbOpenDR = QtWidgets.QCheckBox(dlgNewUpdate)
        self.cbOpenDR.setGeometry(QtCore.QRect(20, 114, 171, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.cbOpenDR.setFont(font)
        self.cbOpenDR.setChecked(False)
        self.cbOpenDR.setObjectName("cbOpenDR")

        self.retranslateUi(dlgNewUpdate)
        self.dlgNewUpdateBtnBox.accepted.connect(dlgNewUpdate.accept) # type: ignore
        self.dlgNewUpdateBtnBox.rejected.connect(dlgNewUpdate.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgNewUpdate)

    def retranslateUi(self, dlgNewUpdate):
        _translate = QtCore.QCoreApplication.translate
        dlgNewUpdate.setWindowTitle(_translate("dlgNewUpdate", "Update Discord Raidkit"))
        self.lblNewUpdateTitle.setText(_translate("dlgNewUpdate", "New Discord Raidkit Update!"))
        self.lblNewUpdateDesc1.setText(_translate("dlgNewUpdate", "There has been a new release of Discord Raidkit"))
        self.lblNewUpdateDesc2.setText(_translate("dlgNewUpdate", "Would you like to view the release page?"))
        self.cbOpenDR.setText(_translate("dlgNewUpdate", "If yes, continue with program?"))
