# Form implementation generated from reading ui file 'InvokeNickAllArgs.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgInvokeNickAllArgs(object):
    def setupUi(self, dlgInvokeNickAllArgs):
        dlgInvokeNickAllArgs.setObjectName("dlgInvokeNickAllArgs")
        dlgInvokeNickAllArgs.resize(320, 150)
        dlgInvokeNickAllArgs.setMinimumSize(QtCore.QSize(320, 150))
        dlgInvokeNickAllArgs.setMaximumSize(QtCore.QSize(320, 150))
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgInvokeNickAllArgs)
        self.btnBox.setGeometry(QtCore.QRect(10, 110, 301, 32))
        self.btnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.leNickname = QtWidgets.QLineEdit(parent=dlgInvokeNickAllArgs)
        self.leNickname.setGeometry(QtCore.QRect(20, 65, 280, 20))
        self.leNickname.setObjectName("leNickname")
        self.lblNickname = QtWidgets.QLabel(parent=dlgInvokeNickAllArgs)
        self.lblNickname.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.lblNickname.setObjectName("lblNickname")

        self.retranslateUi(dlgInvokeNickAllArgs)
        self.btnBox.accepted.connect(dlgInvokeNickAllArgs.accept) # type: ignore
        self.btnBox.rejected.connect(dlgInvokeNickAllArgs.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgInvokeNickAllArgs)

    def retranslateUi(self, dlgInvokeNickAllArgs):
        _translate = QtCore.QCoreApplication.translate
        dlgInvokeNickAllArgs.setWindowTitle(_translate("dlgInvokeNickAllArgs", "Nick All Arguments"))
        self.lblNickname.setText(_translate("dlgInvokeNickAllArgs", "Enter the nickname to nickname all members"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgInvokeNickAllArgs = QtWidgets.QDialog()
    ui = Ui_dlgInvokeNickAllArgs()
    ui.setupUi(dlgInvokeNickAllArgs)
    dlgInvokeNickAllArgs.show()
    sys.exit(app.exec())
