# Form implementation generated from reading ui file 'InvokeRPurge.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgInvokeRPurge(object):
    def setupUi(self, dlgInvokeRPurge):
        dlgInvokeRPurge.setObjectName("dlgInvokeRPurge")
        dlgInvokeRPurge.resize(320, 150)
        dlgInvokeRPurge.setMinimumSize(QtCore.QSize(320, 150))
        dlgInvokeRPurge.setMaximumSize(QtCore.QSize(320, 150))
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgInvokeRPurge)
        self.btnBox.setGeometry(QtCore.QRect(10, 110, 301, 32))
        self.btnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.lblComf = QtWidgets.QLabel(parent=dlgInvokeRPurge)
        self.lblComf.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.lblComf.setObjectName("lblComf")
        self.lblComf2 = QtWidgets.QLabel(parent=dlgInvokeRPurge)
        self.lblComf2.setGeometry(QtCore.QRect(20, 45, 281, 16))
        self.lblComf2.setObjectName("lblComf2")

        self.retranslateUi(dlgInvokeRPurge)
        self.btnBox.accepted.connect(dlgInvokeRPurge.accept) # type: ignore
        self.btnBox.rejected.connect(dlgInvokeRPurge.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgInvokeRPurge)

    def retranslateUi(self, dlgInvokeRPurge):
        _translate = QtCore.QCoreApplication.translate
        dlgInvokeRPurge.setWindowTitle(_translate("dlgInvokeRPurge", "Confirm Role Purge"))
        self.lblComf.setText(_translate("dlgInvokeRPurge", "Are you sure you want Horus to delete"))
        self.lblComf2.setText(_translate("dlgInvokeRPurge", "every role in the given server?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgInvokeRPurge = QtWidgets.QDialog()
    ui = Ui_dlgInvokeRPurge()
    ui.setupUi(dlgInvokeRPurge)
    dlgInvokeRPurge.show()
    sys.exit(app.exec())
