# Form implementation generated from reading ui file 'GenerateTokenGrabber.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgGenerateTokenGrabber(object):
    def setupUi(self, dlgGenerateTokenGrabber):
        dlgGenerateTokenGrabber.setObjectName("dlgGenerateTokenGrabber")
        dlgGenerateTokenGrabber.resize(540, 440)
        dlgGenerateTokenGrabber.setMinimumSize(QtCore.QSize(540, 440))
        dlgGenerateTokenGrabber.setMaximumSize(QtCore.QSize(540, 440))
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgGenerateTokenGrabber)
        self.btnBox.setGeometry(QtCore.QRect(370, 370, 151, 32))
        self.btnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.lblTitle = QtWidgets.QLabel(parent=dlgGenerateTokenGrabber)
        self.lblTitle.setGeometry(QtCore.QRect(20, 20, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.lblWebhookURL = QtWidgets.QLabel(parent=dlgGenerateTokenGrabber)
        self.lblWebhookURL.setGeometry(QtCore.QRect(20, 70, 511, 16))
        self.lblWebhookURL.setObjectName("lblWebhookURL")
        self.leWebhookURL = QtWidgets.QLineEdit(parent=dlgGenerateTokenGrabber)
        self.leWebhookURL.setGeometry(QtCore.QRect(20, 90, 501, 20))
        self.leWebhookURL.setObjectName("leWebhookURL")
        self.lblFolderName = QtWidgets.QLabel(parent=dlgGenerateTokenGrabber)
        self.lblFolderName.setGeometry(QtCore.QRect(20, 130, 511, 16))
        self.lblFolderName.setObjectName("lblFolderName")
        self.leFolderName = QtWidgets.QLineEdit(parent=dlgGenerateTokenGrabber)
        self.leFolderName.setGeometry(QtCore.QRect(20, 150, 501, 20))
        self.leFolderName.setObjectName("leFolderName")
        self.lblRegularPayloadName = QtWidgets.QLabel(parent=dlgGenerateTokenGrabber)
        self.lblRegularPayloadName.setGeometry(QtCore.QRect(20, 190, 511, 16))
        self.lblRegularPayloadName.setObjectName("lblRegularPayloadName")
        self.leRegularPayloadName = QtWidgets.QLineEdit(parent=dlgGenerateTokenGrabber)
        self.leRegularPayloadName.setGeometry(QtCore.QRect(20, 210, 501, 20))
        self.leRegularPayloadName.setObjectName("leRegularPayloadName")
        self.lblHiddenPayloadName = QtWidgets.QLabel(parent=dlgGenerateTokenGrabber)
        self.lblHiddenPayloadName.setGeometry(QtCore.QRect(20, 250, 511, 16))
        self.lblHiddenPayloadName.setObjectName("lblHiddenPayloadName")
        self.leHiddenPayloadName = QtWidgets.QLineEdit(parent=dlgGenerateTokenGrabber)
        self.leHiddenPayloadName.setGeometry(QtCore.QRect(20, 270, 501, 20))
        self.leHiddenPayloadName.setObjectName("leHiddenPayloadName")
        self.chkHavePayloadRunOnStartUp = QtWidgets.QCheckBox(parent=dlgGenerateTokenGrabber)
        self.chkHavePayloadRunOnStartUp.setGeometry(QtCore.QRect(20, 310, 501, 16))
        self.chkHavePayloadRunOnStartUp.setObjectName("chkHavePayloadRunOnStartUp")
        self.label = QtWidgets.QLabel(parent=dlgGenerateTokenGrabber)
        self.label.setGeometry(QtCore.QRect(20, 410, 491, 16))
        self.label.setObjectName("label")

        self.retranslateUi(dlgGenerateTokenGrabber)
        self.btnBox.accepted.connect(dlgGenerateTokenGrabber.accept) # type: ignore
        self.btnBox.rejected.connect(dlgGenerateTokenGrabber.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgGenerateTokenGrabber)

    def retranslateUi(self, dlgGenerateTokenGrabber):
        _translate = QtCore.QCoreApplication.translate
        dlgGenerateTokenGrabber.setWindowTitle(_translate("dlgGenerateTokenGrabber", "Dialog"))
        self.lblTitle.setText(_translate("dlgGenerateTokenGrabber", "Generate Token Grabber"))
        self.lblWebhookURL.setText(_translate("dlgGenerateTokenGrabber", "Enter a Discord channel webhook URL (this is where tokens are sent)"))
        self.lblFolderName.setText(_translate("dlgGenerateTokenGrabber", "Enter a folder name (this will be made on the target machine to store a hidden payload)"))
        self.lblRegularPayloadName.setText(_translate("dlgGenerateTokenGrabber", "Enter the regular payload name (this is the name of the payload the target runs)"))
        self.lblHiddenPayloadName.setText(_translate("dlgGenerateTokenGrabber", "Enter the hidden payload name (this is the name of the payload hidden in the folder)"))
        self.chkHavePayloadRunOnStartUp.setText(_translate("dlgGenerateTokenGrabber", "Have payload add new registry key to run on start-up?"))
        self.label.setText(_translate("dlgGenerateTokenGrabber", "(Please ensure all folder/file names follow Windows conventions)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgGenerateTokenGrabber = QtWidgets.QDialog()
    ui = Ui_dlgGenerateTokenGrabber()
    ui.setupUi(dlgGenerateTokenGrabber)
    dlgGenerateTokenGrabber.show()
    sys.exit(app.exec())
