# Form implementation generated from reading ui file 'InvokeNewWebhookArgs.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgInvokeNewWebhookArgs(object):
    def setupUi(self, dlgInvokeNewWebhookArgs):
        dlgInvokeNewWebhookArgs.setObjectName("dlgInvokeNewWebhookArgs")
        dlgInvokeNewWebhookArgs.resize(320, 200)
        dlgInvokeNewWebhookArgs.setMinimumSize(QtCore.QSize(320, 200))
        dlgInvokeNewWebhookArgs.setMaximumSize(QtCore.QSize(320, 200))
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgInvokeNewWebhookArgs)
        self.btnBox.setGeometry(QtCore.QRect(10, 160, 301, 32))
        self.btnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.lblChannelID = QtWidgets.QLabel(parent=dlgInvokeNewWebhookArgs)
        self.lblChannelID.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.lblChannelID.setObjectName("lblChannelID")
        self.lblName = QtWidgets.QLabel(parent=dlgInvokeNewWebhookArgs)
        self.lblName.setGeometry(QtCore.QRect(20, 95, 271, 16))
        self.lblName.setObjectName("lblName")
        self.leName = QtWidgets.QLineEdit(parent=dlgInvokeNewWebhookArgs)
        self.leName.setGeometry(QtCore.QRect(20, 115, 281, 20))
        self.leName.setObjectName("leName")
        self.leChannelID = QtWidgets.QLineEdit(parent=dlgInvokeNewWebhookArgs)
        self.leChannelID.setGeometry(QtCore.QRect(20, 50, 281, 20))
        self.leChannelID.setObjectName("leChannelID")

        self.retranslateUi(dlgInvokeNewWebhookArgs)
        self.btnBox.accepted.connect(dlgInvokeNewWebhookArgs.accept) # type: ignore
        self.btnBox.rejected.connect(dlgInvokeNewWebhookArgs.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgInvokeNewWebhookArgs)
        dlgInvokeNewWebhookArgs.setTabOrder(self.leChannelID, self.leName)

    def retranslateUi(self, dlgInvokeNewWebhookArgs):
        _translate = QtCore.QCoreApplication.translate
        dlgInvokeNewWebhookArgs.setWindowTitle(_translate("dlgInvokeNewWebhookArgs", "New Webhook Args"))
        self.lblChannelID.setText(_translate("dlgInvokeNewWebhookArgs", "Enter the channel id of the new webhook"))
        self.lblName.setText(_translate("dlgInvokeNewWebhookArgs", "Enter a name for the new webhook"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgInvokeNewWebhookArgs = QtWidgets.QDialog()
    ui = Ui_dlgInvokeNewWebhookArgs()
    ui.setupUi(dlgInvokeNewWebhookArgs)
    dlgInvokeNewWebhookArgs.show()
    sys.exit(app.exec())
