# Form implementation generated from reading ui file 'InvokeAdminArgs.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgInvokeAdminArgs(object):
    def setupUi(self, dlgInvokeAdminArgs):
        dlgInvokeAdminArgs.setObjectName("dlgInvokeAdminArgs")
        dlgInvokeAdminArgs.resize(320, 200)
        dlgInvokeAdminArgs.setMinimumSize(QtCore.QSize(320, 200))
        dlgInvokeAdminArgs.setMaximumSize(QtCore.QSize(320, 200))
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgInvokeAdminArgs)
        self.btnBox.setGeometry(QtCore.QRect(10, 160, 301, 32))
        self.btnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.lblMemberID = QtWidgets.QLabel(parent=dlgInvokeAdminArgs)
        self.lblMemberID.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.lblMemberID.setObjectName("lblMemberID")
        self.lblName = QtWidgets.QLabel(parent=dlgInvokeAdminArgs)
        self.lblName.setGeometry(QtCore.QRect(20, 95, 271, 16))
        self.lblName.setObjectName("lblName")
        self.leName = QtWidgets.QLineEdit(parent=dlgInvokeAdminArgs)
        self.leName.setGeometry(QtCore.QRect(20, 115, 281, 20))
        self.leName.setObjectName("leName")
        self.leMemberID = QtWidgets.QLineEdit(parent=dlgInvokeAdminArgs)
        self.leMemberID.setGeometry(QtCore.QRect(20, 50, 281, 20))
        self.leMemberID.setObjectName("leMemberID")

        self.retranslateUi(dlgInvokeAdminArgs)
        self.btnBox.accepted.connect(dlgInvokeAdminArgs.accept) # type: ignore
        self.btnBox.rejected.connect(dlgInvokeAdminArgs.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgInvokeAdminArgs)
        dlgInvokeAdminArgs.setTabOrder(self.leMemberID, self.leName)

    def retranslateUi(self, dlgInvokeAdminArgs):
        _translate = QtCore.QCoreApplication.translate
        dlgInvokeAdminArgs.setWindowTitle(_translate("dlgInvokeAdminArgs", "Admin Args"))
        self.lblMemberID.setText(_translate("dlgInvokeAdminArgs", "Enter the member id of the new admin"))
        self.lblName.setText(_translate("dlgInvokeAdminArgs", "Enter a name for the new admin role"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgInvokeAdminArgs = QtWidgets.QDialog()
    ui = Ui_dlgInvokeAdminArgs()
    ui.setupUi(dlgInvokeAdminArgs)
    dlgInvokeAdminArgs.show()
    sys.exit(app.exec())
