# Form implementation generated from reading ui file 'InvokeCFloodArgs.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgInvokeCFloodArgs(object):
    def setupUi(self, dlgInvokeCFloodArgs):
        dlgInvokeCFloodArgs.setObjectName("dlgInvokeCFloodArgs")
        dlgInvokeCFloodArgs.resize(320, 200)
        dlgInvokeCFloodArgs.setMinimumSize(QtCore.QSize(320, 200))
        dlgInvokeCFloodArgs.setMaximumSize(QtCore.QSize(320, 200))
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgInvokeCFloodArgs)
        self.btnBox.setGeometry(QtCore.QRect(10, 160, 301, 32))
        self.btnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.lblAmount = QtWidgets.QLabel(parent=dlgInvokeCFloodArgs)
        self.lblAmount.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.lblAmount.setObjectName("lblAmount")
        self.sbAmount = QtWidgets.QSpinBox(parent=dlgInvokeCFloodArgs)
        self.sbAmount.setGeometry(QtCore.QRect(20, 50, 281, 22))
        self.sbAmount.setMinimum(1)
        self.sbAmount.setMaximum(100)
        self.sbAmount.setObjectName("sbAmount")
        self.lblName = QtWidgets.QLabel(parent=dlgInvokeCFloodArgs)
        self.lblName.setGeometry(QtCore.QRect(20, 95, 271, 16))
        self.lblName.setObjectName("lblName")
        self.leName = QtWidgets.QLineEdit(parent=dlgInvokeCFloodArgs)
        self.leName.setGeometry(QtCore.QRect(20, 115, 281, 20))
        self.leName.setObjectName("leName")

        self.retranslateUi(dlgInvokeCFloodArgs)
        self.btnBox.accepted.connect(dlgInvokeCFloodArgs.accept) # type: ignore
        self.btnBox.rejected.connect(dlgInvokeCFloodArgs.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgInvokeCFloodArgs)

    def retranslateUi(self, dlgInvokeCFloodArgs):
        _translate = QtCore.QCoreApplication.translate
        dlgInvokeCFloodArgs.setWindowTitle(_translate("dlgInvokeCFloodArgs", "C-Flood Args"))
        self.lblAmount.setText(_translate("dlgInvokeCFloodArgs", "Enter the number of channels to create"))
        self.lblName.setText(_translate("dlgInvokeCFloodArgs", "Enter a name for the channels"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgInvokeCFloodArgs = QtWidgets.QDialog()
    ui = Ui_dlgInvokeCFloodArgs()
    ui.setupUi(dlgInvokeCFloodArgs)
    dlgInvokeCFloodArgs.show()
    sys.exit(app.exec())
