# Form implementation generated from reading ui file 'InvokeLeave.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgInvokeLeave(object):
    def setupUi(self, dlgInvokeLeave):
        dlgInvokeLeave.setObjectName("dlgInvokeLeave")
        dlgInvokeLeave.resize(320, 150)
        dlgInvokeLeave.setMinimumSize(QtCore.QSize(320, 150))
        dlgInvokeLeave.setMaximumSize(QtCore.QSize(320, 150))
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgInvokeLeave)
        self.btnBox.setGeometry(QtCore.QRect(10, 110, 301, 32))
        self.btnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.lblComf = QtWidgets.QLabel(parent=dlgInvokeLeave)
        self.lblComf.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.lblComf.setObjectName("lblComf")
        self.lblComf2 = QtWidgets.QLabel(parent=dlgInvokeLeave)
        self.lblComf2.setGeometry(QtCore.QRect(20, 45, 281, 16))
        self.lblComf2.setObjectName("lblComf2")

        self.retranslateUi(dlgInvokeLeave)
        self.btnBox.accepted.connect(dlgInvokeLeave.accept) # type: ignore
        self.btnBox.rejected.connect(dlgInvokeLeave.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgInvokeLeave)

    def retranslateUi(self, dlgInvokeLeave):
        _translate = QtCore.QCoreApplication.translate
        dlgInvokeLeave.setWindowTitle(_translate("dlgInvokeLeave", "Leave Server"))
        self.lblComf.setText(_translate("dlgInvokeLeave", "Are you sure you want Horus to leave"))
        self.lblComf2.setText(_translate("dlgInvokeLeave", "the given server?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgInvokeLeave = QtWidgets.QDialog()
    ui = Ui_dlgInvokeLeave()
    ui.setupUi(dlgInvokeLeave)
    dlgInvokeLeave.show()
    sys.exit(app.exec())
