# Form implementation generated from reading ui file 'InvokeMassNukeArgs.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgInvokeMassNukeArgs(object):
    def setupUi(self, dlgInvokeMassNukeArgs):
        dlgInvokeMassNukeArgs.setObjectName("dlgInvokeMassNukeArgs")
        dlgInvokeMassNukeArgs.resize(320, 200)
        dlgInvokeMassNukeArgs.setMinimumSize(QtCore.QSize(320, 200))
        dlgInvokeMassNukeArgs.setMaximumSize(QtCore.QSize(320, 200))
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgInvokeMassNukeArgs)
        self.btnBox.setGeometry(QtCore.QRect(10, 160, 301, 32))
        self.btnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.leMemberID = QtWidgets.QLineEdit(parent=dlgInvokeMassNukeArgs)
        self.leMemberID.setGeometry(QtCore.QRect(20, 100, 280, 20))
        self.leMemberID.setObjectName("leMemberID")
        self.lblMemberID = QtWidgets.QLabel(parent=dlgInvokeMassNukeArgs)
        self.lblMemberID.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.lblMemberID.setObjectName("lblMemberID")
        self.lblMemberID2 = QtWidgets.QLabel(parent=dlgInvokeMassNukeArgs)
        self.lblMemberID2.setGeometry(QtCore.QRect(20, 45, 281, 16))
        self.lblMemberID2.setObjectName("lblMemberID2")
        self.lblNotRequired = QtWidgets.QLabel(parent=dlgInvokeMassNukeArgs)
        self.lblNotRequired.setGeometry(QtCore.QRect(20, 80, 271, 16))
        self.lblNotRequired.setObjectName("lblNotRequired")

        self.retranslateUi(dlgInvokeMassNukeArgs)
        self.btnBox.accepted.connect(dlgInvokeMassNukeArgs.accept) # type: ignore
        self.btnBox.rejected.connect(dlgInvokeMassNukeArgs.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgInvokeMassNukeArgs)

    def retranslateUi(self, dlgInvokeMassNukeArgs):
        _translate = QtCore.QCoreApplication.translate
        dlgInvokeMassNukeArgs.setWindowTitle(_translate("dlgInvokeMassNukeArgs", "Mass Nuke Arguments"))
        self.lblMemberID.setText(_translate("dlgInvokeMassNukeArgs", "Enter the member id of the member"))
        self.lblMemberID2.setText(_translate("dlgInvokeMassNukeArgs", "to exclude from the nuke"))
        self.lblNotRequired.setText(_translate("dlgInvokeMassNukeArgs", "(This field is not required)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgInvokeMassNukeArgs = QtWidgets.QDialog()
    ui = Ui_dlgInvokeMassNukeArgs()
    ui.setupUi(dlgInvokeMassNukeArgs)
    dlgInvokeMassNukeArgs.show()
    sys.exit(app.exec())
