# Form implementation generated from reading ui file 'LatestVersionCheck.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgLatestVersionCheck(object):
    def setupUi(self, dlgLatestVersionCheck):
        dlgLatestVersionCheck.setObjectName("dlgLatestVersionCheck")
        dlgLatestVersionCheck.resize(360, 240)
        dlgLatestVersionCheck.setMinimumSize(QtCore.QSize(360, 240))
        dlgLatestVersionCheck.setMaximumSize(QtCore.QSize(360, 240))
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgLatestVersionCheck)
        self.btnBox.setGeometry(QtCore.QRect(50, 200, 301, 32))
        self.btnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.lblNewVersionAvailable = QtWidgets.QLabel(parent=dlgLatestVersionCheck)
        self.lblNewVersionAvailable.setGeometry(QtCore.QRect(20, 20, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblNewVersionAvailable.setFont(font)
        self.lblNewVersionAvailable.setObjectName("lblNewVersionAvailable")
        self.lblDesc = QtWidgets.QLabel(parent=dlgLatestVersionCheck)
        self.lblDesc.setGeometry(QtCore.QRect(20, 70, 331, 16))
        self.lblDesc.setObjectName("lblDesc")
        self.rdNothing = QtWidgets.QRadioButton(parent=dlgLatestVersionCheck)
        self.rdNothing.setGeometry(QtCore.QRect(30, 100, 321, 16))
        self.rdNothing.setObjectName("rdNothing")
        self.rdOpen = QtWidgets.QRadioButton(parent=dlgLatestVersionCheck)
        self.rdOpen.setGeometry(QtCore.QRect(30, 120, 321, 16))
        self.rdOpen.setObjectName("rdOpen")
        self.rdOpenAndExit = QtWidgets.QRadioButton(parent=dlgLatestVersionCheck)
        self.rdOpenAndExit.setGeometry(QtCore.QRect(30, 140, 321, 16))
        self.rdOpenAndExit.setObjectName("rdOpenAndExit")
        self.chkDoNotShowThisMessageOnStartUpAgain = QtWidgets.QCheckBox(parent=dlgLatestVersionCheck)
        self.chkDoNotShowThisMessageOnStartUpAgain.setGeometry(QtCore.QRect(20, 180, 291, 16))
        self.chkDoNotShowThisMessageOnStartUpAgain.setObjectName("chkDoNotShowThisMessageOnStartUpAgain")

        self.retranslateUi(dlgLatestVersionCheck)
        self.btnBox.accepted.connect(dlgLatestVersionCheck.accept) # type: ignore
        self.btnBox.rejected.connect(dlgLatestVersionCheck.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgLatestVersionCheck)

    def retranslateUi(self, dlgLatestVersionCheck):
        _translate = QtCore.QCoreApplication.translate
        dlgLatestVersionCheck.setWindowTitle(_translate("dlgLatestVersionCheck", "Discord Raidkit - New Version Available"))
        self.lblNewVersionAvailable.setText(_translate("dlgLatestVersionCheck", "New Version Available!"))
        self.lblDesc.setText(_translate("dlgLatestVersionCheck", "A new version of Discord Raidkit has been released."))
        self.rdNothing.setText(_translate("dlgLatestVersionCheck", "Do nothing"))
        self.rdOpen.setText(_translate("dlgLatestVersionCheck", "Open latest version in browser"))
        self.rdOpenAndExit.setText(_translate("dlgLatestVersionCheck", "Open latest version in browser and exit application"))
        self.chkDoNotShowThisMessageOnStartUpAgain.setText(_translate("dlgLatestVersionCheck", "Do not show this message on start-up again."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgLatestVersionCheck = QtWidgets.QDialog()
    ui = Ui_dlgLatestVersionCheck()
    ui.setupUi(dlgLatestVersionCheck)
    dlgLatestVersionCheck.show()
    sys.exit(app.exec())
