# Form implementation generated from reading ui file 'LoginBrowser.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgLoginBrowser(object):
    def setupUi(self, DlgLoginBrowser):
        DlgLoginBrowser.setObjectName("DlgLoginBrowser")
        DlgLoginBrowser.resize(320, 280)
        DlgLoginBrowser.setMinimumSize(QtCore.QSize(320, 280))
        DlgLoginBrowser.setMaximumSize(QtCore.QSize(320, 280))
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DlgLoginBrowser)
        self.buttonBox.setGeometry(QtCore.QRect(10, 230, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lblLoginBrowser = QtWidgets.QLabel(parent=DlgLoginBrowser)
        self.lblLoginBrowser.setGeometry(QtCore.QRect(20, 0, 281, 41))
        self.lblLoginBrowser.setObjectName("lblLoginBrowser")
        self.lblLoginBrowser2 = QtWidgets.QLabel(parent=DlgLoginBrowser)
        self.lblLoginBrowser2.setGeometry(QtCore.QRect(20, 40, 271, 31))
        self.lblLoginBrowser2.setObjectName("lblLoginBrowser2")
        self.lblLoginBrowser3 = QtWidgets.QLabel(parent=DlgLoginBrowser)
        self.lblLoginBrowser3.setGeometry(QtCore.QRect(20, 60, 291, 31))
        self.lblLoginBrowser3.setObjectName("lblLoginBrowser3")
        self.rdChrome = QtWidgets.QRadioButton(parent=DlgLoginBrowser)
        self.rdChrome.setGeometry(QtCore.QRect(20, 130, 151, 21))
        self.rdChrome.setObjectName("rdChrome")
        self.rdFirefox = QtWidgets.QRadioButton(parent=DlgLoginBrowser)
        self.rdFirefox.setGeometry(QtCore.QRect(20, 150, 151, 21))
        self.rdFirefox.setObjectName("rdFirefox")
        self.rdEdge = QtWidgets.QRadioButton(parent=DlgLoginBrowser)
        self.rdEdge.setGeometry(QtCore.QRect(20, 170, 151, 21))
        self.rdEdge.setObjectName("rdEdge")
        self.lblLoginBrowser4 = QtWidgets.QLabel(parent=DlgLoginBrowser)
        self.lblLoginBrowser4.setGeometry(QtCore.QRect(20, 80, 291, 31))
        self.lblLoginBrowser4.setObjectName("lblLoginBrowser4")

        self.retranslateUi(DlgLoginBrowser)
        self.buttonBox.accepted.connect(DlgLoginBrowser.accept) # type: ignore
        self.buttonBox.rejected.connect(DlgLoginBrowser.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DlgLoginBrowser)

    def retranslateUi(self, DlgLoginBrowser):
        _translate = QtCore.QCoreApplication.translate
        DlgLoginBrowser.setWindowTitle(_translate("DlgLoginBrowser", "Select Browser"))
        self.lblLoginBrowser.setText(_translate("DlgLoginBrowser", "Select a browser for Osiris to use:"))
        self.lblLoginBrowser2.setText(_translate("DlgLoginBrowser", "Note: if you do not have the browser\'s"))
        self.lblLoginBrowser3.setText(_translate("DlgLoginBrowser", "webdrivers installed, Osiris will install them -"))
        self.rdChrome.setText(_translate("DlgLoginBrowser", "Chrome"))
        self.rdFirefox.setText(_translate("DlgLoginBrowser", "Firefox"))
        self.rdEdge.setText(_translate("DlgLoginBrowser", "Microsoft Edge"))
        self.lblLoginBrowser4.setText(_translate("DlgLoginBrowser", "this may require a short wait"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgLoginBrowser = QtWidgets.QDialog()
    ui = Ui_DlgLoginBrowser()
    ui.setupUi(DlgLoginBrowser)
    DlgLoginBrowser.show()
    sys.exit(app.exec())
