# Form implementation generated from reading ui file 'InvokeRFloodArgs.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgInvokeRFloodArgs(object):
    def setupUi(self, dlgInvokeRFloodArgs):
        dlgInvokeRFloodArgs.setObjectName("dlgInvokeRFloodArgs")
        dlgInvokeRFloodArgs.resize(320, 200)
        dlgInvokeRFloodArgs.setMinimumSize(QtCore.QSize(320, 200))
        dlgInvokeRFloodArgs.setMaximumSize(QtCore.QSize(320, 200))
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgInvokeRFloodArgs)
        self.btnBox.setGeometry(QtCore.QRect(10, 160, 301, 32))
        self.btnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.lblAmount = QtWidgets.QLabel(parent=dlgInvokeRFloodArgs)
        self.lblAmount.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.lblAmount.setObjectName("lblAmount")
        self.sbAmount = QtWidgets.QSpinBox(parent=dlgInvokeRFloodArgs)
        self.sbAmount.setGeometry(QtCore.QRect(20, 50, 281, 22))
        self.sbAmount.setMinimum(1)
        self.sbAmount.setMaximum(100)
        self.sbAmount.setObjectName("sbAmount")
        self.lblName = QtWidgets.QLabel(parent=dlgInvokeRFloodArgs)
        self.lblName.setGeometry(QtCore.QRect(20, 95, 271, 16))
        self.lblName.setObjectName("lblName")
        self.leName = QtWidgets.QLineEdit(parent=dlgInvokeRFloodArgs)
        self.leName.setGeometry(QtCore.QRect(20, 115, 281, 20))
        self.leName.setObjectName("leName")

        self.retranslateUi(dlgInvokeRFloodArgs)
        self.btnBox.accepted.connect(dlgInvokeRFloodArgs.accept) # type: ignore
        self.btnBox.rejected.connect(dlgInvokeRFloodArgs.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgInvokeRFloodArgs)

    def retranslateUi(self, dlgInvokeRFloodArgs):
        _translate = QtCore.QCoreApplication.translate
        dlgInvokeRFloodArgs.setWindowTitle(_translate("dlgInvokeRFloodArgs", "Role Flood Args"))
        self.lblAmount.setText(_translate("dlgInvokeRFloodArgs", "Enter the number of roles to create"))
        self.lblName.setText(_translate("dlgInvokeRFloodArgs", "Enter a name for the roles"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgInvokeRFloodArgs = QtWidgets.QDialog()
    ui = Ui_dlgInvokeRFloodArgs()
    ui.setupUi(dlgInvokeRFloodArgs)
    dlgInvokeRFloodArgs.show()
    sys.exit(app.exec())
