# Form implementation generated from reading ui file 'HorusClosedMsg.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgHorusClosedMsg(object):
    def setupUi(self, dlgHorusClosedMsg):
        dlgHorusClosedMsg.setObjectName("dlgHorusClosedMsg")
        dlgHorusClosedMsg.resize(400, 240)
        dlgHorusClosedMsg.setMinimumSize(QtCore.QSize(400, 240))
        dlgHorusClosedMsg.setMaximumSize(QtCore.QSize(400, 240))
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgHorusClosedMsg)
        self.btnBox.setGeometry(QtCore.QRect(330, 200, 61, 32))
        self.btnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.lblTitle = QtWidgets.QLabel(parent=dlgHorusClosedMsg)
        self.lblTitle.setGeometry(QtCore.QRect(20, 20, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.label = QtWidgets.QLabel(parent=dlgHorusClosedMsg)
        self.label.setGeometry(QtCore.QRect(20, 80, 431, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=dlgHorusClosedMsg)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 441, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=dlgHorusClosedMsg)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 441, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=dlgHorusClosedMsg)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 441, 16))
        self.label_4.setObjectName("label_4")
        self.chkDoNotShowHorusClosedAgain = QtWidgets.QCheckBox(parent=dlgHorusClosedMsg)
        self.chkDoNotShowHorusClosedAgain.setGeometry(QtCore.QRect(20, 206, 281, 16))
        self.chkDoNotShowHorusClosedAgain.setObjectName("chkDoNotShowHorusClosedAgain")

        self.retranslateUi(dlgHorusClosedMsg)
        self.btnBox.accepted.connect(dlgHorusClosedMsg.accept) # type: ignore
        self.btnBox.rejected.connect(dlgHorusClosedMsg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgHorusClosedMsg)

    def retranslateUi(self, dlgHorusClosedMsg):
        _translate = QtCore.QCoreApplication.translate
        dlgHorusClosedMsg.setWindowTitle(_translate("dlgHorusClosedMsg", "Horus Closed"))
        self.lblTitle.setText(_translate("dlgHorusClosedMsg", "Horus closed."))
        self.label.setText(_translate("dlgHorusClosedMsg", "The Discord API limits bot objects to a connect-once lifespan."))
        self.label_2.setText(_translate("dlgHorusClosedMsg", "This means that, once disconnected, a bot cannot reconnect."))
        self.label_3.setText(_translate("dlgHorusClosedMsg", "If you want to turn Horus on again, restart this application."))
        self.label_4.setText(_translate("dlgHorusClosedMsg", "Remember, Discord affords a limited amount of starts per day. "))
        self.chkDoNotShowHorusClosedAgain.setText(_translate("dlgHorusClosedMsg", "Do not show this pop-up again."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgHorusClosedMsg = QtWidgets.QDialog()
    ui = Ui_dlgHorusClosedMsg()
    ui.setupUi(dlgHorusClosedMsg)
    dlgHorusClosedMsg.show()
    sys.exit(app.exec())
